Revamp news aggregator
brave/news-aggregator pull request #280
Opened 2022-12-21 21:17 UTC by aurangzaib048

This PR includes initial revamp of the news aggregator in more sophisticated way.

- Improved Directory structure
- Added linux script to run the news-aggregator
- Added Data class and improved validation using pydantic
- Updated Dockerfile to install the requirements while building image
- Updated output dir
- Added more lint, formatting and import sorting tools
- Optimized the code base

 **More changes to come**

2022-12-28 12:30 UTC, aurangzaib048 commented on .pre-commit-config.yaml
> +      entry: bandit --quiet -r -x tests/ *.py
entry can also contains arguments, here https://pre-commit.com/#hooks-entry

2022-12-29 13:57 UTC, aurangzaib048 commented on src/image_processor_sandboxed.py
> +            cache_path = config.img_cache_path / cache_fn
Pathlib objects can be appended by `/`

2023-01-03 14:40 UTC, mherrmann reviewed
Hello,

writing because my review was requested after I offered to review PRs here.

I'm deep in another task and unfortunately don't have enough time to read through this extensive PR in detail. But I would like to offer an opinion.

My feeling is that this PR is too big. It does too many things at once. I'm not involved in this project. But my gut feeling is that deploying such a big PR all at once is very risky. (Maybe you considered this, in which case of course my point is mute.)

If I can offer a suggestion, it would be to split this PR into multiple smaller PRs that then get merged, tested and deployed individually. For example: I would have the replacements `'` -> `"` in a separate PR. Merge and ideally deploy that one. Then tackle the next thing, such as adding the type annotations.

2023-01-03 15:59 UTC, mherrmann commented
> these are least changes I can do

Are you sure? I gave several examples above of smaller PRs that could be extracted from this one.

2023-01-03 21:42 UTC, aurangzaib048 commented
Hi @mherrmann We tried to minimize the PR. The things is most of the changes are related to pre-commit hooks which can be ignored. 
The main files that needs a review are `config.py`, `csv_to_json.py`, `csv_to_global_json.py` and structure of the repo. And rest of the files can be ignored (As these only involves format changes)

2023-01-04 22:18 UTC, fmarier requested changes
Partial review, just noting a few things I noticed while skimming through the PR.

All source code files (basically the `.py`) should have the standard Brave copyright statement like [here](https://github.com/brave/brave-core/blob/f3424da24b00217e839b9de87131c3ca7f068e6a/script/generate_licenses.py#L2-L5):

```
# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/. */
```

2023-01-05 12:46 UTC, mherrmann requested changes
Added comments on `config.py`, `csv_to_json.py` and `csv_to_global_json.py`.

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +    """
This comment looks like it is auto-generated boilerplate from pydantic. I'd remove the entire comment.

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +        default=Path(__file__).parent / "output/feed" / "cache"
I'd have either `"output/feed/cache"` here or `"output" / "feed" / "cache"`.

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +    concurrency = max(1, cpu_count())
Is `max(...)` necessary here? I couldn't find anything in the Python docs that says that this might return a non-positive value.

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +    thread_pool_size = max(1, cpu_count() * 10)
Similarly - is `max(...)` necessary?

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +    priv_s3_bucket: str = Field(default="brave-private-cdn-development")
For consistency, I'd have `priv_` or `private_` across all associated settings. So either `private_s3_bucket` or `priv_cdn_canonical_id` and `priv_cdn_cloudfront_canonical_id`.

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +    if CONFIG is None:
Could use `lru_cache` for this.

Instead of:

```
CONFIG: Optional[Configuration] = None
def get_config():
    global CONFIG
    if CONFIG is None:
        CONFIG = Configuration()
    return CONFIG
```

Could do:

```
from functools import lru_cache

@lru_cache()
def get_config():
    return Configuration()
```

2023-01-05 12:46 UTC, mherrmann commented on config.py
> +def set_config(key: str, value: Any) -> None:
I find this name confusing. If I see `get_X` and `set_X`, then I expect them to have the same return and parameter types, respectively. So in other words, from its name, I would have expected `set_config` to take a single parameter, of type `Configuration`.

I would remove this function and just write `get_config().attr = value` where needed.

2023-01-05 12:46 UTC, mherrmann commented on lib/__init__.py
> +from .utils import (
Without having read the entire code, I think I'd have all those functions in top-level `utils.py` instead of in `lib/__init__.py`.

2023-01-05 12:46 UTC, mherrmann commented on src/csv_to_json.py
> +def parse_publishers():
To me, `parse_...` is strictly a read operation. But this function does a lot of writing too. I'd rename it to `main()`, since it's called from `if __name__ == '__main__'` below.

2023-01-05 12:46 UTC, mherrmann commented on src/csv_to_global_json.py
> +def parse_global_publishers():
I'd rename this to `main()`.

2023-01-05 12:46 UTC, mherrmann commented on src/csv_to_global_json.py
> +def get_publisher_by_id(
I think this function can be removed if we turn `publishers` below into a dict. See below.

2023-01-05 12:46 UTC, mherrmann commented on src/csv_to_global_json.py
> +    publishers: list[PublisherGlobal] = []
I think this function can be rewritten as follows (untested):

```
    publishers = {}
    source_files = config.sources_dir.glob("sources.*_*.csv")
    for source_file in source_files:
        locale = locales_finder.findall(source_file.name)[0]
        with open(source_file, "r") as publisher_file_pointer:
            publisher_reader = csv.DictReader(publisher_file_pointer)
            for data in publisher_reader:
                try:
                    publisher: PublisherGlobal = PublisherGlobal(**data)

                    if publisher.publisher_id not in publishers:
                        publisher.favicon_url = favicons_lookup.get(
                            publisher.site_url, None
                        )
                        publisher.cover_info = cover_infos_lookup.get(
                            publisher.site_url,
                            {"cover_url": None, "background_color": None},
                        )

                        locale_builder = LocaleModel(**data)
                        locale_builder.locale = locale
                        publisher.locales.append(locale_builder)
                        publishers[publisher.publisher_id] = publisher
                    else:
                        existing_publisher = publishers[publisher.publisher_id]
                        locale_builder = LocaleModel(**data)
                        locale_builder.locale = locale
                        existing_publisher.locales.append(locale_builder)

                except ValidationError as e:
                    logger.info(f"{e} on {data}")

    ...
```

2023-01-05 14:31 UTC, tarikdem commented on bin/start.sh
> +  echo "Waiting for squid to start..."
Is Squid used for news-aggregator in EKS? Seems like a better idea to have this in the ops repo (or wherever else the containers needs to run) as some sort of probe when defining the containers in a pod. The container itself shouldn't be aware of any other services that run alongside it.

2023-01-05 14:31 UTC, tarikdem commented on bin/start.sh
> +if [[ "$task" = "csv-to-json" ]]; then
Could this script be simplified by extracting the code that's repeated for every case in a function, and then calling that function for each task?

Also, consider using the python script name as the task name, then there would be no need for various cases (if-else statements), aside from the shell and run-all tasks.

2023-01-05 16:08 UTC, aurangzaib048 commented on bin/start.sh
> +  echo "Waiting for squid to start..."
Yes Squid used for news-aggregator, I was thinking that can we run squid as sidecar?

2023-01-05 16:43 UTC, tarikdem commented on bin/start.sh
> +  echo "Waiting for squid to start..."
That sounds good. We can use the same approach as in today-ops.

2023-01-06 18:59 UTC, tarikdem submitted a review, later dismissed

2023-01-09 06:48 UTC, mherrmann requested changes
In addition to my inline comments, I think `src/__init__.py` should be removed.

2023-01-09 06:48 UTC, mherrmann commented on src/csv_to_global_json.py
> +from lib.utils import get_cover_infos_lookup, get_favicons_lookup, upload_file
This should be `from utils import ...`. A package that is called `lib` is (imho) completely vacuous. A straightforward solution would be to move `utils.py` into `src/`, and adding `src/` to the PYTHONPATH if it isn't there already.

2023-01-09 06:48 UTC, mherrmann commented on src/csv_to_global_json.py
> +        with open(source_file, "r") as publisher_file_pointer:
You could omit the `"r"` here as it is the default.

2023-01-11 08:07 UTC, mherrmann requested changes

2023-01-11 08:07 UTC, mherrmann commented on src/favicons_covers/cover_images.py
> +from src.favicons_covers.color import color_length, hex_color, is_transparent
From my perspective, the same caveat applies for `src` as it did for `lib` before: This is a vacuous package name. `src` should be added to the PYTHONPATH and these imports should not mention `src`. So eg. they should be:

```
import image_processor_sandboxed
from favicons_covers.color import color_length, hex_color, is_transparent
from utils import get_all_domains, upload_file
```

Likewise for other occurrences of `src` in imports.

2023-01-11 17:59 UTC, mherrmann requested changes
I think `lib/__init__.py` can be removed.

2023-01-12 14:28 UTC, mherrmann approved these changes
`config.py`, `csv_to_json.py` and `csv_to_global_json.py` lgtm now. The rest of the PR is too complex for me to all take in in a reasonable amount of time. As I commented above, my advice would be to split this PR into multiple smaller ones that can then be reviewed, tested and deployed separately. From my perspective, the complexity of this PR brings with it a significant risk of breakage.

2023-01-12 14:35 UTC, aurangzaib048 commented
Thanks for taking the time to review this PR, We will deploy it on the staging and see everything is working as expected then we will move it to the prod.

2023-01-12 15:04 UTC, tarikdem approved these changes

2023-01-16 21:03 UTC, merged