Include the healthcheck script
brave/news-aggregator pull request #554
Opened 2023-09-29 20:21 UTC by porteron

2023-10-02 15:50 UTC, aurangzaib048 requested changes

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +	s3_client = boto_session.client("s3")
We can import `s3_client` from utils, we have defined there

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +
To get access to `config`
`from config import get_config
config = get_config()`

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +	upload_file("latest-updated.json", bucket_name, "latest-updated.json")
`config.pub_s3_bucket`

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +	sources_dir = "../sources"
we have `sources_dir` defined in config we can get this from there and the type of the `sources_dir` is Path which provides more that `os` utils

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +from datetime import datetime, timedelta
to access the s3 client `from utils import s3_client`

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +			break
Check the 80% files working we should consider it as success.

2023-10-02 15:50 UTC, aurangzaib048 commented on src/healthcheck.py
> +	upload_file("latest-updated.json", bucket_name, "latest-updated.json")
after create the status file we should send the sentry alert to channel which regions are failed.

2023-10-04 05:58 UTC, porteron commented
@aurangzaib048 I addressed your PR feedback, last item I still need to address is hooking up to Sentry.

2023-10-04 11:53 UTC, aurangzaib048 requested changes

2023-10-04 11:53 UTC, aurangzaib048 commented on src/healthcheck.py
> +            s3_file_keys.append(os.path.join(sources_dir, filename))
We don’t need this cause sources dir will only contains sources files

2023-10-04 11:53 UTC, aurangzaib048 commented on src/healthcheck.py
> +    upload_file("latest-updated.json", config.pub_s3_bucket, "latest-updated.json")
We should delete the `latest-updated.json` if the 80% criteria is not fulfilled.

2023-10-04 11:53 UTC, aurangzaib048 commented on src/healthcheck.py
> +    expiry_threshold = 0.8  # 80%
We should keep track of the files which are being updated and send sentry alert to the our news alerts channel.

2023-10-04 16:47 UTC, porteron commented on src/healthcheck.py
> +            s3_file_keys.append(os.path.join(sources_dir, filename))
ah yes need to remove this

2023-10-04 18:13 UTC, porteron commented on src/healthcheck.py
> +    upload_file("latest-updated.json", config.pub_s3_bucket, "latest-updated.json")
I dont think we want to delete the file. We just want to change the status in the file `status :'expired'` then the better uptime can search for the keyword `expired`

2023-10-04 18:16 UTC, porteron commented on src/healthcheck.py
> +    expiry_threshold = 0.8  # 80%
the `file_modification_dates = {}` keeps track of the files so we can send that in the alert. It just has the last updated date for each file, maybe there should be a helper value that explicitly says "expired"

2023-10-05 21:28 UTC, aurangzaib048 approved these changes
We have to add the cronjob of the script in ops repo as well.

2023-10-06 19:30 UTC, porteron commented
Strange the test keeps failing like that

2023-10-06 19:49 UTC, merged